# docker-compose.yml
version: '3'
networks:
  todoapp-net:
services:
 
  mysql:
    image: fredfredburger/mysql-local:1.1.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-local
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
      
      
    networks:
      - todoapp-net
  pythonapp:
    image: fredfredburger/todoapp:2.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=mysql-local
      - MYSQL_PORT=3306
      - ENGINE=mysql.connector.django
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
volumes:
  todoapp-db-data:
